[build]
  base = "client"
  publish = "dist"
  command = "npm install && npx vite build"

[build.environment]
  NODE_VERSION = "18.16.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
  VITE_SERVER_URL = "https://mind-map-xoy6.onrender.com"

[context.deploy-preview.environment]
  NODE_ENV = "production"

[context.branch-deploy.environment]
  NODE_ENV = "production" 